# Generated by Django 4.0.10 on 2023-03-29 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_generalsettings_phonegeneral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonegeneral',
            name='general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number', to='blog.generalsettings'),
        ),
        migrations.CreateModel(
            name='EmailGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='blog.generalsettings')),
            ],
        ),
    ]
