# Generated by Django 4.0.10 on 2023-03-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_phonegeneral_general_emailgeneral'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralSettings',
            new_name='ContactSettings',
        ),
        migrations.RenameModel(
            old_name='EmailGeneral',
            new_name='EmailContact',
        ),
        migrations.RenameModel(
            old_name='PhoneGeneral',
            new_name='PhoneContact',
        ),
    ]
