# Generated by Django 4.0.10 on 2023-03-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_generalsettings_contactsettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsettings',
            options={'verbose_name': 'Contact About', 'verbose_name_plural': 'Contact About'},
        ),
    ]
