# Generated by Django 4.0.10 on 2023-03-29 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_contactsettings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'About Settings',
                'verbose_name_plural': 'About Settings',
            },
        ),
        migrations.CreateModel(
            name='SectionAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='section_images')),
                ('text', models.TextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='blog.about')),
            ],
        ),
    ]
