# Generated by Django 4.0.10 on 2023-03-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_portfoliocategory_portfolio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocategory',
            name='project_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
