# Generated by Django 3.2.18 on 2023-03-29 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='main_image',
            field=models.ImageField(null=True, upload_to='portfolio_images'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='video',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='blog.portfolio')),
            ],
        ),
    ]
