# Generated by Django 3.2.18 on 2023-04-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_blog_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.FileField(null=True, upload_to='author_pp'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='main_image',
            field=models.FileField(null=True, upload_to='portfolio_images'),
        ),
        migrations.AlterField(
            model_name='portfolioimages',
            name='image',
            field=models.FileField(null=True, upload_to='portfolio_images'),
        ),
        migrations.AlterField(
            model_name='sectionabout',
            name='image',
            field=models.FileField(null=True, upload_to='section_images'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(null=True, upload_to='service_images'),
        ),
    ]
