# Generated by Django 3.2.18 on 2023-04-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20230403_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentStage', models.CharField(max_length=3000)),
                ('chooseWebSite', models.CharField(max_length=3000)),
                ('professionalNeed', models.CharField(max_length=3000)),
                ('duration', models.CharField(max_length=3000)),
                ('name', models.CharField(max_length=3000)),
                ('surname', models.CharField(max_length=3000)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=3000)),
                ('description', models.TextField()),
                ('projectDeatils', models.TextField()),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
